In [6]:
import cv2
import numpy as np
import pandas as pd
from tensorflow.keras.datasets import cifar10
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### 1. KNN

In [19]:
(X_train, y_train), (X_test, y_test) = cifar10.load_data()
print(X_train.shape, X_test.shape)

(50000, 32, 32, 3) (10000, 32, 32, 3)


In [22]:
y_train = y_train.astype(np.float32)
y_test = y_test.astype(np.float32)
y_train

array([[6.],
       [9.],
       [9.],
       ...,
       [9.],
       [1.],
       [1.]], dtype=float32)

In [23]:
X_train = X_train.reshape(X_train.shape[0], -1).astype(np.float32)
X_test = X_test.reshape(X_test.shape[0], -1).astype(np.float32)
X_test.shape

(10000, 3072)

In [24]:
knn = cv2.ml.KNearest_create()
knn.train(X_train, cv2.ml.ROW_SAMPLE, y_train)

True

In [35]:
_, result, _, _ = knn.findNearest(X_test, 5)
print(result)

[[2.]
 [8.]
 [8.]
 ...
 [5.]
 [6.]
 [4.]]


In [38]:
count = 0
for i in (y_test == result):
    if i == [True]:
        count +=1
print(f'Accuracy: {100*count/y_test.shape[0]}')

Accuracy: 33.98


In [41]:
print(accuracy_score(y_test, result))
print(classification_report(y_test, result))

0.3398
              precision    recall  f1-score   support

         0.0       0.38      0.54      0.45      1000
         1.0       0.65      0.20      0.31      1000
         2.0       0.23      0.45      0.30      1000
         3.0       0.29      0.22      0.25      1000
         4.0       0.24      0.51      0.33      1000
         5.0       0.39      0.22      0.28      1000
         6.0       0.35      0.25      0.29      1000
         7.0       0.68      0.21      0.32      1000
         8.0       0.40      0.66      0.50      1000
         9.0       0.70      0.14      0.23      1000

    accuracy                           0.34     10000
   macro avg       0.43      0.34      0.33     10000
weighted avg       0.43      0.34      0.33     10000



### 2. SVM

In [46]:
y_train1 = y_train.astype(np.uint)
y_train1

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint64)

In [47]:
svm = cv2.ml.SVM_create()
svm.setKernel(cv2.ml.SVM_LINEAR)
svm.setType(cv2.ml.SVM_C_SVC)
svm.train(X_train, cv2.ml.ROW_SAMPLE, y_train1)

True

In [48]:
_, result = svm.predict(X_test)

In [51]:
result1 = result.astype(np.uint)
y_test1 = y_test.astype(np.uint)

In [52]:
print(accuracy_score(y_test, result))
print(classification_report(y_test, result))

0.1492
              precision    recall  f1-score   support

         0.0       0.11      0.05      0.07      1000
         1.0       0.18      0.33      0.23      1000
         2.0       0.12      0.05      0.07      1000
         3.0       0.11      0.20      0.14      1000
         4.0       0.22      0.04      0.07      1000
         5.0       0.16      0.35      0.22      1000
         6.0       0.18      0.08      0.11      1000
         7.0       0.18      0.16      0.17      1000
         8.0       0.10      0.10      0.10      1000
         9.0       0.16      0.13      0.14      1000

    accuracy                           0.15     10000
   macro avg       0.15      0.15      0.13     10000
weighted avg       0.15      0.15      0.13     10000



- Do ảnh không phải linear nên sử dụng SVM_LINEAR cho ra kết quả rất tệ. Dùng RBF sẽ đạt kết quả accuracy cao hơn nhưng thời gian train có thể lâu hơn rất nhiều (Có thể dùng PCA để giảm số feature xuống)

In [53]:
svm.setKernel(cv2.ml.SVM_RBF)
svm.train(X_train, cv2.ml.ROW_SAMPLE, y_train1)
_, result2 = svm.predict(X_test)
print(accuracy_score(y_test, result2))
print(classification_report(y_test, result2))

KeyboardInterrupt: 